-- MySQL Script generated by MySQL Workbench
-- 07/07/16 15:58:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SIMCardComponent
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SIMCardComponent` ;

-- -----------------------------------------------------
-- Schema SIMCardComponent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIMCardComponent` DEFAULT CHARACTER SET utf8 ;
USE `SIMCardComponent` ;

-- -----------------------------------------------------
-- Table `SIMCardComponent`.`Tenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`Tenant` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`Tenant` (
  `uuid` CHAR(30) NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(1000) NULL,
  `apikey_id` CHAR(50) NULL,
  `apikey_secret` CHAR(50) NULL,
  `status` CHAR(10) NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  `topic` VARCHAR(100) NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `topic_UNIQUE` (`topic` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`Group` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`Group` (
  `uuid` CHAR(30) NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(1000) NULL,
  `status` CHAR(10) NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `tenantUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `GROUPTENANTUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `GROUPTENANTUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`Organization` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`Organization` (
  `uuid` CHAR(30) NOT NULL,
  `name` VARCHAR(256) NULL,
  `description` VARCHAR(1000) NULL,
  `status` CHAR(10) NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `tenantUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `ORGANIZATIONTENANTUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `ORGANIZATIONTENANTUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`Directory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`Directory` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`Directory` (
  `uuid` CHAR(30) NOT NULL,
  `name` VARCHAR(256) NULL,
  `status` CHAR(10) NULL,
  `description` VARCHAR(1000) NULL,
  `snRuleUUID` CHAR(30) NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `tenantUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `DIRECTORYTENANTUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `DIRECTORYTENANTUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`OrganizationMembership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`OrganizationMembership` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`OrganizationMembership` (
  `uuid` CHAR(30) NOT NULL,
  `organizationUUID` CHAR(30) NULL,
  `storeUUID` CHAR(30) NULL,
  `tenantUUID` CHAR(30) NULL,
  `type` CHAR(10) NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `OrganizationMembershipOrganizationUUID_idx` (`organizationUUID` ASC),
  INDEX `OrganizationMembershipTenantUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `OrganizationMembershipTenantUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrganizationMembershipOrganizationUUID`
    FOREIGN KEY (`organizationUUID`)
    REFERENCES `SIMCardComponent`.`Organization` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`GroupMembership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`GroupMembership` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`GroupMembership` (
  `uuid` CHAR(30) NOT NULL,
  `groupUUID` CHAR(30) NULL,
  `simCardUUID` CHAR(30) NULL,
  `tenantUUID` CHAR(30) NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `GroupMembershipGroupUUID_idx` (`groupUUID` ASC),
  INDEX `GroupMembershipTenantUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `GroupMembershipTenantUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GroupMembershipGroupUUID`
    FOREIGN KEY (`groupUUID`)
    REFERENCES `SIMCardComponent`.`Group` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`SIMCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`SIMCard` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`SIMCard` (
  `uuid` CHAR(30) NOT NULL,
  `ICCID` VARCHAR(256) NULL,
  `IMSI` VARCHAR(256) NULL,
  `phone` VARCHAR(11) NULL,
  `openCardData` DATETIME NULL,
  `packageType` VARCHAR(45) NULL,
  `batchNO` VARCHAR(45) NULL,
  `carrier` VARCHAR(256) NULL,
  `package` VARCHAR(256) NULL,
  `status` VARCHAR(10) NULL,
  `businessStatus` VARCHAR(45) NULL,
  `activeData` DATETIME NULL,
  `useData` DATETIME NULL,
  `sn` VARCHAR(45) NULL,
  `shareFlow` CHAR(10) NULL,
  `testPeriodTo` DATETIME NULL,
  `silentPeriodTo` DATETIME NULL,
  `description` VARCHAR(1000) NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `directoryUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `SIMCardDirectoryUUID_idx` (`directoryUUID` ASC),
  CONSTRAINT `SIMCardDirectoryUUID`
    FOREIGN KEY (`directoryUUID`)
    REFERENCES `SIMCardComponent`.`Directory` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`Flow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`Flow` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`Flow` (
  `uuid` CHAR(30) NOT NULL,
  `type` VARCHAR(100) NULL,
  `beginTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `total` INT NULL,
  `customData` JSON NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `simCardUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `FLOWSIMCARDUUID_idx` (`simCardUUID` ASC),
  CONSTRAINT `FLOWSIMCARDUUID`
    FOREIGN KEY (`simCardUUID`)
    REFERENCES `SIMCardComponent`.`SIMCard` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`BatchNORule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`BatchNORule` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`BatchNORule` (
  `uuid` CHAR(30) NOT NULL,
  `rule` VARCHAR(256) NULL,
  `complementCode` VARCHAR(256) NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `tenantUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `BatchNORuleTenantUUID_idx` (`tenantUUID` ASC),
  CONSTRAINT `BatchNORuleTenantUUID`
    FOREIGN KEY (`tenantUUID`)
    REFERENCES `SIMCardComponent`.`Tenant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`BatchNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`BatchNumber` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`BatchNumber` (
  `uuid` CHAR(30) NOT NULL,
  `batchNumber` VARCHAR(256) NULL,
  `createAt` DATETIME NULL,
  `modifiedAt` DATETIME NULL,
  `batchNORuleUUID` CHAR(30) NULL,
  `deleteFlag` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`uuid`),
  INDEX `BatchNumberBatchNORuleUUID_idx` (`batchNORuleUUID` ASC),
  CONSTRAINT `BatchNumberBatchNORuleUUID`
    FOREIGN KEY (`batchNORuleUUID`)
    REFERENCES `SIMCardComponent`.`BatchNORule` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIMCardComponent`.`SerialNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIMCardComponent`.`SerialNumber` ;

CREATE TABLE IF NOT EXISTS `SIMCardComponent`.`SerialNumber` (
  `batchNumber` BIGINT NOT NULL,
  `createAt` DATETIME NULL,
  PRIMARY KEY (`batchNumber`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
